spring.application.name=38-SpringBoot-Web-Mvc-EMS

# server port 
server.port=8080

# Web Mvc viewresolver Properties 

spring.mvc.view.prefix=/views/
spring.mvc.view.suffix=.jsp

#enable All actuator endpoints

management.endpoints.web.exposure.include=*
management.endpoints.web.exposure.exclude=beans,mappings,heapdump

#active profile (change Environment)

spring.profiles.active=dev