spring.application.name=38-SpringBoot-Web-Mvc-EMS

# server port 
server.port=8080

# Web Mvc viewresolver Properties 

spring.mvc.view.prefix=/views/
spring.mvc.view.suffix=.jsp

#enable All actuator endpoints

management.endpoints.web.exposure.include=*
management.endpoints.web.exposure.exclude=beans,mappings,heapdump

#active profile (change Environment)

spring.profiles.active=dev
server.port=9090

# Database Properties 

spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
spring.datasource.url=jdbc:mysql://localhost:3306/reg50
spring.datasource.username=root
spring.datasource.password=root

# Data JPA Properties 
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

# Web Mvc Properties 

spring.mvc.view.prefix=/views/
spring.mvc.view.suffix=.jsp